[features]
seeds = false
skip-lint = false
[programs.devnet]
tut2 = "3MGnQXb5wnxnxXLThkaN5Ri3CpZq4PmTQQZujS1VUisU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
