[features]
seeds = false
skip-lint = false
[programs.devnet]
tut2 = "DiaL51hpMhAm46z8E8x4Ku8ipeccnJ4ryg5Ki8NahG1r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vhits/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
